# Generated by Django 5.2.8 on 2025-11-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule_template',
            table='schedule_template',
        ),
    ]
