# Generated by Django 5.2.8 on 2025-11-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_schedule_template_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schedule_template',
            table=None,
        ),
    ]
