# Generated by Django 5.2.8 on 2025-11-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attendance_table_alter_schedule_template_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
        migrations.AlterModelTable(
            name='schedule_template',
            table='schedule_template',
        ),
    ]
