# Generated by Django 5.2.8 on 2025-11-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_attendance_table_alter_schedule_template_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='balls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField()),
                ('dop_balls', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'balls',
            },
        ),
    ]
